name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare, build and deploy
        uses: iktnb/github-utils/.github/actions/prepare-and-build-for-gh-pages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: "20"
          site_url: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          build-env-vars: |
            NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
            GTM_TOKEN=${{ secrets.GTM_TOKEN }}
          deploy-command: npm run deploy